import 'package:clinic_doctor_interview/features/doctors/data/models/doctor_model.dart';

List<DoctorModel> doctorsList = [
  DoctorModel(
    id: 1,
    name: 'Dr. Alice Morgan',
    specialty: 'Oncologist',
    rating: 4.7,
    hourlyPrice: 6,
    reviewCount: 116,
    hospitalName: 'Harmony Hospital',
    imageUrl: 'https://randomuser.me/api/portraits/men/1.jpg',
    availableDates: ["Sun 16", "Mon 10", "Thu 13"],
    availableTimes: ["10:30 AM", "2:30 PM"],
    description:
        '''Respected in the field for dedication and attention to detail.''',
  ),
  DoctorModel(
    id: 2,
    name: 'Dr. Ethan Grant',
    specialty: 'Neurologist',
    rating: 4.8,
    hourlyPrice: 6,
    reviewCount: 154,
    hospitalName: 'Sunrise Medical Center',
    imageUrl: 'https://randomuser.me/api/portraits/women/2.jpg',
    availableDates: ["Tue 11", "Wed 12", "Thu 13"],
    availableTimes: ["4:00 PM", "2:30 PM"],
    description:
        '''A highly experienced specialist offering compassionate and personalized care.''',
  ),
  DoctorModel(
    id: 3,
    name: 'Dr. Olivia Hayes',
    specialty: 'Neurologist',
    rating: 4.8,
    hourlyPrice: 7,
    reviewCount: 91,
    hospitalName: 'Green Valley Clinic',
    imageUrl: 'https://randomuser.me/api/portraits/men/3.jpg',
    availableDates: ["Wed 12", "Thu 13", "Mon 10"],
    availableTimes: ["2:30 PM", "4:00 PM"],
    description:
        '''Respected in the field for dedication and attention to detail.''',
  ),
  DoctorModel(
    id: 4,
    name: 'Dr. Noah Carter',
    specialty: 'Neurologist',
    rating: 4.7,
    hourlyPrice: 7,
    reviewCount: 149,
    hospitalName: 'Sunrise Medical Center',
    imageUrl: 'https://randomuser.me/api/portraits/women/4.jpg',
    availableDates: ["Tue 11", "Sat 15", "Thu 13"],
    availableTimes: ["1:00 PM", "10:30 AM"],
    description:
        '''A highly experienced specialist offering compassionate and personalized care.''',
  ),
  DoctorModel(
    id: 5,
    name: 'Dr. Ava Brooks',
    specialty: 'Radiologist',
    rating: 4.7,
    hourlyPrice: 6,
    reviewCount: 104,
    hospitalName: 'Oceanview Medical',
    imageUrl: 'https://randomuser.me/api/portraits/men/5.jpg',
    availableDates: ["Sun 16", "Fri 14", "Mon 10"],
    availableTimes: ["1:00 PM", "4:00 PM"],
    description:
        '''Combines years of expertise with modern treatment techniques.''',
  ),
  DoctorModel(
    id: 6,
    name: 'Dr. Liam Scott',
    specialty: 'Radiologist',
    rating: 4.9,
    hourlyPrice: 7,
    reviewCount: 71,
    hospitalName: 'Green Valley Clinic',
    imageUrl: 'https://randomuser.me/api/portraits/women/6.jpg',
    availableDates: ["Sun 16", "Sat 15", "Fri 14"],
    availableTimes: ["2:30 PM", "10:30 AM"],
    description:
        '''Combines years of expertise with modern treatment techniques.''',
  ),
  DoctorModel(
    id: 7,
    name: 'Dr. Emma Bell',
    specialty: 'Orthopedic',
    rating: 5.0,
    hourlyPrice: 5,
    reviewCount: 92,
    hospitalName: 'Summit Health Center',
    imageUrl: 'https://randomuser.me/api/portraits/men/7.jpg',
    availableDates: ["Thu 13", "Sat 15", "Mon 10"],
    availableTimes: ["10:30 AM", "4:00 PM"],
    description:
        '''Passionate about improving patient outcomes with thorough consultations.''',
  ),
  DoctorModel(
    id: 8,
    name: 'Dr. James Young',
    specialty: 'Cardiologist',
    rating: 4.9,
    hourlyPrice: 7,
    reviewCount: 171,
    hospitalName: 'Sunrise Medical Center',
    imageUrl: 'https://randomuser.me/api/portraits/women/8.jpg',
    availableDates: ["Wed 12", "Sun 16", "Sat 15"],
    availableTimes: ["2:30 PM", "4:00 PM"],
    description:
        '''Known for a patient-first approach and outstanding diagnostic skills.''',
  ),
  DoctorModel(
    id: 9,
    name: 'Dr. Mia Gray',
    specialty: 'Pediatrician',
    rating: 4.6,
    hourlyPrice: 5,
    reviewCount: 87,
    hospitalName: 'Harmony Hospital',
    imageUrl: 'https://randomuser.me/api/portraits/men/9.jpg',
    availableDates: ["Tue 11", "Mon 10", "Fri 14"],
    availableTimes: ["1:00 PM", "4:00 PM"],
    description:
        '''Cares deeply for children's health and emotional wellbeing.''',
  ),
  DoctorModel(
    id: 10,
    name: 'Dr. Lucas Adams',
    specialty: 'Orthopedic',
    rating: 4.8,
    hourlyPrice: 6,
    reviewCount: 123,
    hospitalName: 'Green Valley Clinic',
    imageUrl: 'https://randomuser.me/api/portraits/women/10.jpg',
    availableDates: ["Thu 13", "Sat 15", "Sun 16"],
    availableTimes: ["10:30 AM", "1:00 PM"],
    description: '''Expert in joint and bone recovery treatments.''',
  ),
  DoctorModel(
    id: 11,
    name: 'Dr. Chloe Martin',
    specialty: 'Cardiologist',
    rating: 4.7,
    hourlyPrice: 7,
    reviewCount: 112,
    hospitalName: 'Oceanview Medical',
    imageUrl: 'https://randomuser.me/api/portraits/men/11.jpg',
    availableDates: ["Mon 10", "Tue 11", "Wed 12"],
    availableTimes: ["4:00 PM", "2:30 PM"],
    description: '''Blends modern technology with heartfelt care.''',
  ),
  DoctorModel(
    id: 12,
    name: 'Dr. Henry Lewis',
    specialty: 'Dermatologist',
    rating: 4.9,
    hourlyPrice: 6,
    reviewCount: 99,
    hospitalName: 'Summit Health Center',
    imageUrl: 'https://randomuser.me/api/portraits/women/12.jpg',
    availableDates: ["Thu 13", "Fri 14", "Sun 16"],
    availableTimes: ["1:00 PM", "10:30 AM"],
    description:
        '''Skilled in treating all skin types with advanced therapies.''',
  ),
  DoctorModel(
    id: 13,
    name: 'Dr. Lily Turner',
    specialty: 'Dermatologist',
    rating: 4.8,
    hourlyPrice: 6,
    reviewCount: 106,
    hospitalName: 'Green Valley Clinic',
    imageUrl: 'https://randomuser.me/api/portraits/men/13.jpg',
    availableDates: ["Wed 12", "Sat 15", "Sun 16"],
    availableTimes: ["10:30 AM", "1:00 PM"],
    description: '''Known for clear, effective skin treatment plans.''',
  ),
  DoctorModel(
    id: 14,
    name: 'Dr. Samuel Ross',
    specialty: 'Orthopedic',
    rating: 4.9,
    hourlyPrice: 7,
    reviewCount: 101,
    hospitalName: 'Sunrise Medical Center',
    imageUrl: 'https://randomuser.me/api/portraits/women/14.jpg',
    availableDates: ["Fri 14", "Sat 15", "Mon 10"],
    availableTimes: ["4:00 PM", "2:30 PM"],
    description: '''Helps patients regain mobility and strength quickly.''',
  ),
  DoctorModel(
    id: 15,
    name: 'Dr. Grace Hill',
    specialty: 'Cardiologist',
    rating: 4.6,
    hourlyPrice: 5,
    reviewCount: 89,
    hospitalName: 'Oceanview Medical',
    imageUrl: 'https://randomuser.me/api/portraits/men/15.jpg',
    availableDates: ["Tue 11", "Thu 13", "Sun 16"],
    availableTimes: ["10:30 AM", "1:00 PM"],
    description:
        '''Combines research and experience for exceptional heart care.''',
  ),
  DoctorModel(
    id: 16,
    name: 'Dr. Elijah Ward',
    specialty: 'Radiologist',
    rating: 4.7,
    hourlyPrice: 6,
    reviewCount: 120,
    hospitalName: 'Harmony Hospital',
    imageUrl: 'https://randomuser.me/api/portraits/women/16.jpg',
    availableDates: ["Wed 12", "Mon 10", "Fri 14"],
    availableTimes: ["1:00 PM", "2:30 PM"],
    description: '''Detailed diagnostics using state-of-the-art tools.''',
  ),
  DoctorModel(
    id: 17,
    name: 'Dr. Zoe Diaz',
    specialty: 'Pediatrician',
    rating: 4.9,
    hourlyPrice: 7,
    reviewCount: 130,
    hospitalName: 'Summit Health Center',
    imageUrl: 'https://randomuser.me/api/portraits/men/17.jpg',
    availableDates: ["Thu 13", "Fri 14", "Sun 16"],
    availableTimes: ["10:30 AM", "4:00 PM"],
    description:
        '''Highly trusted for gentle and effective care of children.''',
  ),
  DoctorModel(
    id: 18,
    name: 'Dr. Daniel Scott',
    specialty: 'ENT Specialist',
    rating: 4.8,
    hourlyPrice: 5,
    reviewCount: 111,
    hospitalName: 'Oceanview Medical',
    imageUrl: 'https://randomuser.me/api/portraits/women/18.jpg',
    availableDates: ["Tue 11", "Wed 12", "Sat 15"],
    availableTimes: ["1:00 PM", "2:30 PM"],
    description:
        '''Specialist in both surgical and non-invasive ENT treatments.''',
  ),
  DoctorModel(
    id: 19,
    name: 'Dr. Aria Evans',
    specialty: 'Neurologist',
    rating: 4.7,
    hourlyPrice: 6,
    reviewCount: 100,
    hospitalName: 'Sunrise Medical Center',
    imageUrl: 'https://randomuser.me/api/portraits/men/19.jpg',
    availableDates: ["Fri 14", "Sun 16", "Mon 10"],
    availableTimes: ["4:00 PM", "10:30 AM"],
    description: '''Dedicated to comprehensive brain and spine care.''',
  ),
  DoctorModel(
    id: 20,
    name: 'Dr. Jack Murphy',
    specialty: 'Oncologist',
    rating: 4.8,
    hourlyPrice: 7,
    reviewCount: 115,
    hospitalName: 'Harmony Hospital',
    imageUrl: 'https://randomuser.me/api/portraits/women/20.jpg',
    availableDates: ["Thu 13", "Tue 11", "Sat 15"],
    availableTimes: ["1:00 PM", "4:00 PM"],
    description:
        '''Cares deeply for patient journey and recovery from cancer.''',
  ),
  DoctorModel(
    id: 21,
    name: 'Dr. Nora Bennett',
    specialty: 'Cardiologist',
    rating: 4.6,
    hourlyPrice: 5,
    reviewCount: 97,
    hospitalName: 'Green Valley Clinic',
    imageUrl: 'https://randomuser.me/api/portraits/men/21.jpg',
    availableDates: ["Mon 10", "Wed 12", "Fri 14"],
    availableTimes: ["2:30 PM", "10:30 AM"],
    description: '''Strong focus on prevention and lifestyle change.''',
  ),
  DoctorModel(
    id: 22,
    name: 'Dr. Isaac Reed',
    specialty: 'Dermatologist',
    rating: 4.9,
    hourlyPrice: 6,
    reviewCount: 88,
    hospitalName: 'Summit Health Center',
    imageUrl: 'https://randomuser.me/api/portraits/women/22.jpg',
    availableDates: ["Thu 13", "Sat 15", "Tue 11"],
    availableTimes: ["4:00 PM", "2:30 PM"],
    description: '''Clear, simple treatment plans for every skin condition.''',
  ),
  DoctorModel(
    id: 23,
    name: 'Dr. Ella James',
    specialty: 'ENT Specialist',
    rating: 4.8,
    hourlyPrice: 6,
    reviewCount: 121,
    hospitalName: 'Oceanview Medical',
    imageUrl: 'https://randomuser.me/api/portraits/men/23.jpg',
    availableDates: ["Fri 14", "Mon 10", "Sun 16"],
    availableTimes: ["10:30 AM", "1:00 PM"],
    description: '''Excellent communicator and ENT surgeon.''',
  ),
  DoctorModel(
    id: 24,
    name: 'Dr. Logan Price',
    specialty: 'Orthopedic',
    rating: 4.7,
    hourlyPrice: 6,
    reviewCount: 108,
    hospitalName: 'Sunrise Medical Center',
    imageUrl: 'https://randomuser.me/api/portraits/women/24.jpg',
    availableDates: ["Wed 12", "Thu 13", "Sat 15"],
    availableTimes: ["4:00 PM", "2:30 PM"],
    description: '''Focused on joint preservation and sports injuries.''',
  ),
  DoctorModel(
    id: 25,
    name: 'Dr. Harper Cox',
    specialty: 'Radiologist',
    rating: 4.9,
    hourlyPrice: 5,
    reviewCount: 102,
    hospitalName: 'Harmony Hospital',
    imageUrl: 'https://randomuser.me/api/portraits/men/25.jpg',
    availableDates: ["Tue 11", "Sun 16", "Fri 14"],
    availableTimes: ["2:30 PM", "10:30 AM"],
    description: '''Fast and accurate imaging analysis.''',
  ),
  DoctorModel(
    id: 26,
    name: 'Dr. Mason Long',
    specialty: 'Pediatrician',
    rating: 4.8,
    hourlyPrice: 7,
    reviewCount: 114,
    hospitalName: 'Oceanview Medical',
    imageUrl: 'https://randomuser.me/api/portraits/women/26.jpg',
    availableDates: ["Thu 13", "Sat 15", "Sun 16"],
    availableTimes: ["1:00 PM", "4:00 PM"],
    description: '''Trusted by parents for years of excellent child care.''',
  ),
  DoctorModel(
    id: 27,
    name: 'Dr. Scarlett Bailey',
    specialty: 'Cardiologist',
    rating: 4.7,
    hourlyPrice: 6,
    reviewCount: 95,
    hospitalName: 'Green Valley Clinic',
    imageUrl: 'https://randomuser.me/api/portraits/men/27.jpg',
    availableDates: ["Mon 10", "Wed 12", "Fri 14"],
    availableTimes: ["10:30 AM", "1:00 PM"],
    description: '''Balances diagnostics with empathy and trust.''',
  ),
  DoctorModel(
    id: 28,
    name: 'Dr. Aiden Powell',
    specialty: 'Neurologist',
    rating: 4.9,
    hourlyPrice: 6,
    reviewCount: 110,
    hospitalName: 'Summit Health Center',
    imageUrl: 'https://randomuser.me/api/portraits/women/28.jpg',
    availableDates: ["Thu 13", "Sat 15", "Tue 11"],
    availableTimes: ["4:00 PM", "2:30 PM"],
    description: '''Focused on brain wellness through modern therapies.''',
  ),
  DoctorModel(
    id: 29,
    name: 'Dr. Natalie Ward',
    specialty: 'Oncologist',
    rating: 4.8,
    hourlyPrice: 5,
    reviewCount: 99,
    hospitalName: 'Oceanview Medical',
    imageUrl: 'https://randomuser.me/api/portraits/men/29.jpg',
    availableDates: ["Sun 16", "Tue 11", "Mon 10"],
    availableTimes: ["1:00 PM", "4:00 PM"],
    description: '''Supportive and informed cancer treatment plans.''',
  ),
  DoctorModel(
    id: 30,
    name: 'Dr. William Foster',
    specialty: 'ENT Specialist',
    rating: 4.6,
    hourlyPrice: 6,
    reviewCount: 90,
    hospitalName: 'Harmony Hospital',
    imageUrl: 'https://randomuser.me/api/portraits/women/30.jpg',
    availableDates: ["Wed 12", "Thu 13", "Sat 15"],
    availableTimes: ["10:30 AM", "2:30 PM"],
    description: '''Great listener and detail-oriented specialist.''',
  ),
];
